### ISSUE TITLE
Wheels in rviz do not move when motors do. 

### ISSUE THREAD

**Issue by andreucm** [JavierRubia/Garrinator#4]
We observe that the wheels in rviz do not move when motors do. 

All joint names at registered at hardware interfaces have been reviewed. 

Still looking for the bug ...

**Comment by andreucm** [comment]
@JavierRubia , can you please check the last version at add_joint_state_controller branch (please pull it before!)

Let me know (replying here) how it works 

thanks

**Comment by andreucm** [comment]
@JavierRubia , please check the code with the motors. Pull the last commit at branch add_joint_state_controller (177e5b6495bf773fede9c9730dee35314b2a5595)

Let me know replying here how it works. 

thanks

**Comment by JavierRubia** [comment]
The wheels has spawned wrong in the Rviz, all of them are in the origin, also there's an error in the Rviz that says `There is no transform from (any rim/roller) to base link `.

**Comment by andreucm** [comment]
ok, let me check more things ...

**Comment by andreucm** [comment]
@JavierRubia , pull and check it again, 

Please report the output of "rostopic list"

thanks

**Comment by JavierRubia** [comment]
The motors move but the wheels still don't the "rostopic list" is the following:

/clicked_point
/initialpose
/joint_states
/move_base_simple/goal
/rosout
/rosout_agg
/tf
/tf_static

it gives you any clue?

**Comment by andreucm** [comment]
@JavierRubia , Please report output of `rostopic echo /joint_states`
 thanks

**Comment by JavierRubia** [comment]
It gives no output just the cursor blinking.

**Comment by andreucm** [comment]
ok, 
Please report output of `rostopic info /joint_states`
thanks

**Comment by andreucm** [comment]
( @JavierRubia  All the outputs I'm requesting should be **while** the execution is live )

**Comment by JavierRubia** [comment]
The echo gives no output while it's alive.

The info gaves the following:
Type: sensor_msgs/JointState

Publishers: None

Subscribers: 
 * /robot_state_publisher (http://javier-GF63-Thin-9SC:45249/)
 * /rostopic_10456_1584641118687 (http://javier-GF63-Thin-9SC:39885/)

**Comment by andreucm** [comment]
ok, nobody is publishing joint_states, and this is not good. I'll review it.

**Comment by andreucm** [comment]
Hi @JavierRubia , please pull and test again!
Please report output of `rostopic info /joint_states`
thanks

**Comment by JavierRubia** [comment]
Good news it partially works!
The output of the rostopic info is:
Type: sensor_msgs/JointState

Publishers: 
 * /hw_if_node (http://javier-GF63-Thin-9SC:33895/)

Subscribers: 
 * /robot_state_publisher (http://javier-GF63-Thin-9SC:34837/)

The wheels started moving in the simulation, I've reduced the sleep time to 0.01 to keep the info in the controller fresh and it moved in the rviz.

The bad thing here is that only moves the rims, the rollers keep unable to find transform to the base so they appear in the middle of the base and not in the rim as they should be.

**Comment by andreucm** [comment]
@JavierRubia , please pull and check again. 
I've added 'roller_front_left_rim_front_left_joint' joint to the joint_state_controller config file, so you should see that this joint displays correctly in rviz. 
Let me know
thanks
