### ISSUE TITLE
hw_if_node: symbol lookup error 

### ISSUE THREAD

**Issue by JavierRubia** [JavierRubia/Garrinator#7]
Hi @andreucm 

At branch https://github.com/JavierRubia/Garrinator/tree/omni_4_controller, when launching pops the following error just after trying to load the omni_4controller:

`/home/javier/catkin_ws/devel/lib/garrinator_hardware_interface/hw_if_node: symbol lookup error: /home/javier/catkin_ws/devel/lib//libomni4_controller.so: undefined symbol: _ZN16omni4_controller15Omni4ControllerC1Ev
`

fter some research I've found the command ` c++filt` which decodes that symbol and gives the following: 
omni4_controller::Omni4Controller::Omni4Controller()

I've been looking for that expression in the code but I couldn't find it, so figured out that there is not explicitly written in it, also I've tried to modify the name in 
https://github.com/JavierRubia/Garrinator/blob/9d880098fd1dea4f54839425ea5a93b20e132102/omni4_controller/controller_plugins.xml#L1
but ended up with it did not find it, even though I've made a catkin_make right after.

Anyway I' left the code as it was.

Do you have any idea where that symbol occurs? I've read that some people have similar problems and solve them by re installing the library itself, but I've erased both _devel_ and _build_ folders in order to recompile everything but the issue persists.

Could you help me please?

Thank you.

**Comment by andreucm** [comment]
Hi @JavierRubia  , 

please pull the branch https://github.com/JavierRubia/Garrinator/tree/omni_4_controller  and test with the robot.

and report the result here, 

thanks
